### ISSUE TITLE
Fasity-auth throws and error after an asynchronous call is completed

### ISSUE THREAD

**Issue by magixus** [fastify/fastify-auth#138]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.27.1

### Plugin version

3.0.1

### Node.js version

14.17.6

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Ubuntu 20.04.3 LTS

### Description

I'am trying to build an authentication plugin using  fastify, fastify-auth, and aws cognito.

The fastify application is generated using [create-fastify-app][1] 

1. **My router looks like this:** 

```js

module.exports = async function (fastify, opts) {
    fastify
        .post(
            '/service',
            { ...options, schema: { ...options.schema, body: { ...schema, } } },
            fastify.auth([fastify.verify]),
            crudController.addNew
        )
```

2. **My fastify.verify decorate function looks like this**

```jsconst fp = require('fastify-plugin')
const jwt = require('jsonwebtoken')
const jwkToPem = require('jwk-to-pem')

module.exports = fp(async (fastify, opts) => {

    fastify
        .register(require('fastify-auth'))

        .decorate("jwk", { keys: [{ ... //all the secrets here }] })

        .decorate("verify", verifyJWT)

    function verifyJWT(request, reply) {

        const pemjwk = jwkToPem(fastify.jwk.keys[0])

        if (request.body && request.body.failureWithReply) {
            reply.code(401).send({ error: 'Unauthorized' })
            return Promise.reject(new Error())
        }

        if (!request.headers.token) {
            reply
                .type('application/json')
                .code(401)
                .send({ error: 'Missing token header' })
            return Promise.reject(new Error('Missing token header'))
        }

        return new Promise((resolve, reject) => {
            jwt.verify(request.headers.token, pemjwk, { algorithms: ['RS256'] }, (err, payload) => {
                if (err) {
                    return reject(err)
                }
                resolve(payload)
            })
        }).then((payload) => {
            fastify.log.info(`User ${payload['cognito:username']} authenticated !`)
        }).catch((error) => {
            reply
                .code(401)
                .send(error)
            throw new Error(error)
        })

    }
})
```

`**fastify.verify**` decorator just verify the JWT token, return the payload if user is authentic otherwise throw an error.

Fastify log the message "user authenticated!" everything works perfect so far. 

But when the request is completed, I got the following error that crash the application:

```js
22:06:35 ✨ incoming request POST xxx /api/v1/auth/login
22:06:37 ✨ request completed 1.4s
22:06:48 ✨ incoming request POST xxx /api/v1/service
22:06:48 ✨ User ousssddfs authenticated !
TypeError: that.done is not a function
    at Auth.completeAuth (/workstation/dev/haflago/backend/node_modules/fastify-auth/auth.js:115:12)
    at Auth.onAuth (/workstation/dev/haflago/backend/node_modules/fastify-auth/auth.js:89:21)
    at /workstation/dev/haflago/backend/node_modules/fastify-auth/auth.js:79:43
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
[nodemon] app crashed - waiting for file changes before starting...
``` 

I also compared my code with their test example, and it looks pretty similar !! 

Did anybody get this error before ? 

  [1]: https://github.com/davidedantonio/create-fastify-app

### Steps to Reproduce

1. Create a plugin to register fastify-auth & decorte verify function: 
```js

const fp = require('fastify-plugin')
const jwt = require('jsonwebtoken')
const jwkToPem = require('jwk-to-pem')

module.exports = fp(async (fastify, opts) => {

    fastify
        .register(require('fastify-auth'))
        .decorate("verify", async (request, reply) => {

            if (request.body && request.body.failureWithReply) {
                reply.code(401).send({ error: 'Unauthorized' })
                return Promise.reject(new Error())
            }

            if (!request.headers.token) {
                reply
                    .type('application/json')
                    .code(401)
                    .send({ error: 'Missing token header' })
                return Promise.reject(new Error('Missing token header'))
            }

            return new Promise((resolve, reject) => {
                jwt.verify(request.headers.token, pemjwk, { algorithms: ['RS256'] }, (err, payload) => {
                    if (err) {
                        return reject(err)
                    }
                    resolve(payload)
                })
            }).then((payload) => {
                fastify.log.info(`User ${payload.user is authenticated !`)
                reply
                    .code(200)
                    .send({ message: "Authentication successful !" })
                return reply
            }).catch((error) => {
                reply
                    .code(401)
                    .send(error)
                throw new Error(error)
            })

        })
})
```

2. Create a route that take `preHandler` as fastify-auth : 

```js
module.exports = async function (fastify, opts) {
    fastify
        .post(
            '/service',
            fastify.auth([fastify.verify]),
            crudController.addNew
        )
```

3. Consume the API with postman : 
```
[nodemon] starting `fastify start ./src/index.js`
22:33:28 ✨ DB is provided at :  mongodb://localhost:27028/halago
22:33:28 ✨ Database is connected
22:33:28 ✨ Server listening at http://127.0.0.1:9898
22:33:34 ✨ incoming request POST xxx /api/v1/service
TypeError: that.done is not a function
    at Auth.completeAuth (/workstation/dev/haflago/backend/node_modules/fastify-auth/auth.js:115:12)
    at Auth.onAuth (/workstation/dev/haflago/backend/node_modules/fastify-auth/auth.js:89:21)
    at /workstation/dev/haflago/backend/node_modules/fastify-auth/auth.js:79:43
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
[nodemon] app crashed - waiting for file changes before starting...
```

### Expected Behavior

Fastify-auth decorator log the decoded JWT token and app doesn't crash.

**Comment by mcollina** [comment]
Your route definition is not correct. You need to use fastify.auth in a hook:

```js
module.exports = async function (fastify, opts) {
    fastify
        .post(
            '/service',
            { ...options, onRequest: fastify.auth([fastify.verify]), schema: { ...options.schema, body: { ...schema, } } },
            crudController.addNew
        )

```

**Comment by magixus** [comment]
Thank you so much @mcollina 

I've added a `preHandler` instead of `onRequest` as I wanted to inject some properties in request with the decoded JWT value. Do you think it's better ?

```js
fastify
        .decorateRequest('user', '')
        .post(
            '/service',
            { ...options, preHandler: fastify.auth([fastify.verify]), schema: { ...options.schema, body: { ...schema, } } },
            crudController.addNew,
        )
``` 

Fastify docs doesn't refer to `including hooks in options` with shorthand declaration routes.
